Oldtape::Application.routes.draw do
  #get "build_mixtape/create/:mid/:sid/:order" => 'build_mixtape#create'
  #get "build_mixtape/destroy"

  # Automatic routes generated by Devise
  devise_for :users

  # Default route
  root :to => 'artists#index'

  # Resourceful Routes
  resources :artists, :mixtapes, :build_mixtape
  resources :albums, :only => [:index, :show]
	resources :songs,  :only => [:index, :show]

	# Nested Resourceful Routes
	# resources :artists do
	#   resources :albums
	# end

	# We can define additional routes for albums except nested resources above like this.
	# resources :albums
  # get '/albums/:id' => 'albums#show'
end
