Oldtape::Application.routes.draw do
  get "songs/index"

  get "songs/show"

	# Automatic routes generated by Devise
  devise_for :users

  # Default route
  root :to => 'artists#index'

  # Resourceful Routes
  resources :artists, :albums, :songs

	# Nested Resourceful Routes
	# resources :artists do
	#   resources :albums
	# end

	# We can define additional routes for albums except nested resources above like this.
	# resources :albums
  # get '/albums/:id' => 'albums#show'
end
